### PR TITLE
Making YIN an addon (~10x speed up)

### PR DESCRIPTION
**Pull request by cristovao-trevisan**
Hello,
just like the title says I've made an addon for the YIN algorithm. It should be easy to make the same for the others using my code as a template. Why? The 10x speed up of course.

The tests are not passing because of some hard-coded values with too much precision, what should I do about it? Ex.:
```diff
[
-  261.32142976170746
-  293.6807450488696
-  322.9017937618668
-  348.76007881394395
-  392.239055336809
-  436.3365869674357
-  490.674096485507
-  524.0830270494633
+  261.32143206655036
+  293.68075206633904
+  322.9018005020524
+  348.76007762751016
+  392.23906125008307
+  436.3365797777694
+  490.67410541944446
+  524.0830227479873
]
```

### CODE REVIEW

**Comment by cristovao-trevisan** [comment]
Just realized that you may want to keep browser compatibility, so I will post my fork as another package to npm (node-pitchfinder or something like it)

**Comment by cristovao-trevisan** [comment]
I've done it, it's now on https://github.com/cristovao-trevisan/node-pitchfinder and it's published to npm. I've also implemented the MacLeod's algorithm (at some point in pure js if you want to copy it - just look at the commits if so). As it is a different module now, I'm closing this PR.

**Comment by peterkhayes** [comment]
Nice work!  I'd like to keep this browser-compatible, as I was using it for a browser-based music app.  But this looks like great work for anyone who wants a node version.  I can add this to the readme.

**Comment by cristovao-trevisan** [comment]
That would be awesome. Thanks

**Comment by peterkhayes** [comment]
done!

**Pull request closed without merging**
