### PR TITLE
now using babel 6

### LINKED ISSUE #9: ReferenceError: [BABEL] Using removed Babel 5 option
Module build failed: ReferenceError: [BABEL] /Users/dan/stuff/visual-experiments/node_modules/pitchfinder/index.js: Using removed Babel 5 option: /Users/dan/stuff/visual-experiments/node_modules/pitchfinder/.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error (/Users/dan/stuff/visual-experiments/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/dan/stuff/visual-experiments/node_modules/babel-core/lib/transformation/file/options/option-manager.js:216:20)
    at OptionManager.init (/Users/dan/stuff/visual-experiments/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/dan/stuff/visual-experiments/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/dan/stuff/visual-experiments/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/dan/stuff/visual-experiments/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/dan/stuff/visual-experiments/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/dan/stuff/visual-experiments/node_modules/babel-loader/index.js:131:12)
 @ ./index.jsx 28:19-41

### PR DESCRIPTION
**Pull request by fxlemire**
Fixes #9

### CODE REVIEW

**Comment by peterkhayes** [comment]
I think you need up bump a few more things - the babel version for instance.  Can you make sure everything builds properly and then I'll merge?

**Comment by fxlemire** [comment]
Not sure what you mean by `up bump a few more things - the babel version for instance`. Babel has been bumped up to `^6.26.0`. Babel now uses `babel-cli`, `babel` is deprecated.

It builds properly on my machine, i'm actually using the lib folder from this branch right now on a personal project. Only 2 tests are failing but it is a float precision error (e.g. actual 348.7600776275102, expected 348.76007762751016) that would need to be fixed in another branch.

The travis error seems to be due to travis not building with the proper dependencies.
`Error: Cannot find module 'babel-core/register'`
`babel-core/register` comes with babel-cli.

The one thing I'm unsure of is if it's okay to manually bump up the package.json version or do you have some deploy tool that will take care of it?

**Comment by peterkhayes** [comment]
Yeah, what I mean is, can you update the `package.json` to contain updated dependencies, such that a fresh install can `npm run build` without crashing?

**Comment by fxlemire** [comment]
You mean even eslint, mocha and all?

Because unless my understanding fails me, as far as babel goes, the `package.json` builds perfectly fine and noeeds no further changes. `babel-cli` is not a global requirement. It is the new way to use babel. See [babeljs.io](http://babeljs.io/)

If you clone [my fork](https://github.com/fxlemire/pitchfinder) (which is in the state of the current PR), you will see that `npm i && npm run build` works just fine.

**Comment by peterkhayes** [comment]
Oh, sorry!  I must have misread the diff.  I didn't see that you updated the package.json.  I'll merge this in.

**Pull request merged**
