### PR TITLE
Fixed typo, changed lower pitch cutoff from 88 to 80 as it was in Tar…

### PR DESCRIPTION
**Pull request by euphonialabs**
…soDSP implementation, algorithm now functional

### CODE REVIEW

**Comment by matthewleon** [comment]
@peterkhayes Any comments or updates on this?

**Comment by peterkhayes** [comment]
Currently there aren't tests and the linting doesn't pass.  I'll take a look and see if I can fix this up.

**Comment by peterkhayes** [comment]
Ok, I had to fix a ton of little errors, so I fixed this from a new branch.  But the MacLeod method should be in there now, version `2.0.5`

**Comment by matthewleon** [comment]
Thanks!

**Pull request closed without merging**
